name: Test Tunnelier

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      
      - name: Install WireGuard tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard-tools

      - name: Set up Docker Compose
        run: docker compose version || docker-compose version

      - name: Up Docker compose
        run: |
          docker compose up -d
          sleep 5

      - name: Run Tests
        run: go test -v ./cmd/tunnelier

      - name: Down Docker compose
        if: always()
        run: docker compose down
